### ISSUE TITLE
Configuration Typo

### ISSUE THREAD

**Issue by YWang1008** [ghostseven/homebridge-hs-plug#2]
**Describe The Bug:**

In the project description, the following configuration option was provided

**`name`** [optional] this is the username of your kasa app login

Instead, it should be:

**_`user`_** [optional] this is the username of your kasa app login

**Comment by ghostseven** [comment]
Thank you for this, I will get this updated.

**Comment by ghostseven** [comment]
Fixed.

**Comment by YWang1008** [comment]
Thank you!

Meanwhile, thanks a million for making this project! This helped solve a huge issue for me! 😀

**Comment by ghostseven** [comment]
No worries, I will admit it is very rough and ready and when I get a chance I want to sit down and work on it some more!  Glad it is working for you.
